#!/bin/bash
read -e -p "Name des PCs: " -i "B414-" NAME
IP="$(echo "$NAME" | rev | cut -d"-" -f1 | rev)"
echo -e "auto lo\niface lo inet loopback\nauto eth0\niface eth0 inet static\n  address 10.10.8.$IP/16\n  gateway 10.10.0.1\n  hostname $NAME" > /etc/network/interfaces
echo -e "search lan\nnameserver 1.1.1.1" > /etc/resolv.conf
/etc/init.d/networking restart > /dev/null 2>&1
echo -e "http://dl-cdn.alpinelinux.org/alpine/v3.16/main\nhttp://dl-cdn.alpinelinux.org/alpine/v3.16/community\nhttp://dl-cdn.alpinelinux.org/alpine/edge/main\nhttp://dl-cdn.alpinelinux.org/alpine/edge/community\nhttp://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories
echo "Installiere Pakete..."
apk update > /dev/null 2>&1
apk add nano libvirt-daemon libvirt libvirt-qemu qemu-img qemu-system-x86_64 qemu-modules openrc dbus polkit virt-manager terminus-font xf86-video-intel xf86-video-nouveau xf86-video-fbdev xf86-video-vesa i3wm i3status xterm udev ovmf > /dev/null 2>&1
echo "Starte Dienste..."
rc-update add libvirtd > /dev/null 2>&1
rc-update add dbus > /dev/null 2>&1
rc-update add libvirt-guests > /dev/null 2>&1
rc-service libvirtd start > /dev/null 2>&1
rc-service libvirt-guests start > /dev/null 2>&1
cat /etc/modules | grep tun || echo tun >> /etc/modules
modprobe tun > /dev/null 2>&1
echo "Konfiguriere System..."
setup-xorg-base > /dev/null 2>&1
echo "exec i3" > /root/.xinitrc
wget https://raw.githubusercontent.com/MrNightfloor/kvm-host/main/udev/rules.d/11-media-by-label-auto-mount.rules -P /etc/udev/rules.d/ > /dev/null 2>&1
mkdir -p /root/.config/i3
wget https://raw.githubusercontent.com/MrNightfloor/kvm-host/main/i3/config -P /root/.config/i3/ > /dev/null 2>&1
udevadm control --reload-rules > /dev/null 2>&1
read -p "Bitte USB Stick einstecken (weiter mit Enter)"
echo "Importiere Virtuelle Maschiene..."
wget https://raw.githubusercontent.com/MrNightfloor/kvm-host/main/libvirt/qemu/win11.xml -P /etc/libvirt/qemu/ > /dev/null 2>&1
virsh define /etc/libvirt/qemu/win11.xml > /dev/null 2>&1
echo "Setup erfolgreich!"
startx > /dev/null 2>&1 &
exit 0
