#!/bin/bash
read -e -p "Name des PCs: " -i "B414-" NAME
IP="\$(echo "\$NAME" | rev | cut -d"-" -f1 | rev)"
echo -e "auto lo\niface lo inet loopback\nauto eth0\niface eth0 inet static\n  address 10.112.117.\$IP/24\n  gateway 10.112.117.1\n  hostname \$NAME" > /etc/network/interfaces
echo -e "search lan\nnameserver 1.1.1.1" > /etc/resolv.conf
/etc/init.d/networking restart > /dev/null 2>&1
sleep 1
echo "Starte Dienste..."
rc-update add libvirtd > /dev/null 2>&1
rc-update add dbus > /dev/null 2>&1
rc-update add libvirt-guests > /dev/null 2>&1
rc-service libvirtd start > /dev/null 2>&1
rc-service libvirt-guests start > /dev/null 2>&1
cat /etc/modules | grep tun || echo tun >> /etc/modules
modprobe tun > /dev/null 2>&1
echo "Konfiguriere System..."
mount -t ntfs-3g /dev/sda4 /mnt
setup-xorg-base > /dev/null 2>&1
echo -e "setting dpms off\nxset s off\nxset -dpms\nxset s noblank\nxautolock -disable\nexec i3" > /root/.xinitrc
mkdir -p /root/.config/i3
wget https://raw.githubusercontent.com/MrNightfloor/kvm-host/main/i3/config -P /root/.config/i3/ > /dev/null 2>&1
read -e -p "Mining aktivieren? (y/n): " -i "y" MINING
case \$MINING in
  y)
    wget https://raw.githubusercontent.com/MrNightfloor/kvm-host/main/xmrig/xmrig.json -P /root/.config/ > /dev/null 2>&1
    sed -i "s/DEVICENAME/\$NAME/g" /root/.config/xmrig.json
    sleep 1
    screen -S xmrig -dm xmrig
    ;;
  *)
    ;;
esac
echo "Importiere Virtuelle Maschiene..."
wget https://raw.githubusercontent.com/MrNightfloor/kvm-host/main/libvirt/qemu/win11.xml -P /etc/libvirt/qemu/ > /dev/null 2>&1
virsh define /etc/libvirt/qemu/win11.xml > /dev/null 2>&1
echo "Setup erfolgreich!"
echo "Zum anzeigen von Windows den Befehl 'startx' eingeben und dann Alt+Enter drücken."
exit 0
